export const ALL_SERVICES = ["Netflix", "Prime", "Max", "Hulu", "Disney+", "Tubi", "Other"];

export const SEED = {
  films: [
    { id: 1, n: "Whiplash", y: 2014, d: "Damien Chazelle", rt: 106, mood: "tense", svc: "Netflix", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A young drummer at an elite conservatory collides with a ruthless instructor who accepts nothing short of greatness." },
    { id: 2, n: "Parasite", y: 2019, d: "Bong Joon-ho", rt: 132, mood: "tense", svc: "Max", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A struggling family cons its way into a wealthy household — until the arrangement unravels in ways nobody sees coming." },
    { id: 3, n: "Mad Max: Fury Road", y: 2015, d: "George Miller", rt: 120, mood: "tense", svc: "Max", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "In a scorched wasteland, a drifter and a rebel commander flee a tyrant in one long, roaring chase for freedom." },
    { id: 4, n: "The Social Network", y: 2010, d: "David Fincher", rt: 120, mood: "tense", svc: "Prime", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "The founding of Facebook becomes a battlefield of lawsuits, betrayal, and raw ambition." },
    { id: 5, n: "Arrival", y: 2016, d: "Denis Villeneuve", rt: 116, mood: "scifi", svc: "Prime", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A linguist races to decode the language of alien visitors — and what she learns rewrites her whole life." },
    { id: 6, n: "Get Out", y: 2017, d: "Jordan Peele", rt: 104, mood: "horror", svc: "Netflix", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A weekend meeting his girlfriend's family turns into a nightmare hiding beneath polite smiles." },
    { id: 7, n: "La La Land", y: 2016, d: "Damien Chazelle", rt: 128, mood: "light", svc: "Netflix", status: "watched", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "An actress and a jazz pianist chase their dreams — and each other — through a bittersweet, technicolor Los Angeles." },
    { id: 8, n: "The Nice Guys", y: 2016, d: "Shane Black", rt: 116, mood: "light", svc: "Netflix", status: "watchlist", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A hapless PI and a hired enforcer stumble through 1970s LA trying to crack a case neither is remotely qualified for." },
    { id: 9, n: "Coherence", y: 2013, d: "James Ward Byrkit", rt: 89, mood: "scifi", svc: "Tubi", status: "watchlist", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A dinner party goes sideways when a passing comet quietly fractures reality among eight friends." },
    { id: 10, n: "Palm Springs", y: 2020, d: "Max Barbakow", rt: 90, mood: "light", svc: "Hulu", status: "watchlist", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "Two wedding guests get stuck in the same inescapable day and decide to make it everyone else's problem." },
    { id: 11, n: "Sicario", y: 2015, d: "Denis Villeneuve", rt: 121, mood: "tense", svc: "Netflix", status: "watchlist", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "An idealistic FBI agent is pulled into the moral fog of a covert war against a cartel." },
    { id: 12, n: "Everything Everywhere All at Once", y: 2022, d: "Daniels", rt: 139, mood: "scifi", svc: "Prime", status: "watchlist", elo: 1500, w: 0, l: 0, rating: null, note: "", syn: "A laundromat owner discovers she must hop between universes to save every version of her family." },
  ],
  predictions: [],
  faceoffCount: 0,
  spins: { committed: 0, honored: 0 },
  night: null,
  services: [...ALL_SERVICES],
  handle: "",
  vetoesLeft: 2,
  notifSeen: { trending: [], svc: {} },
  nightLog: [],
  everSpun: false,
  nextId: 13,
};

export const TRENDING = [
  { tid: "t1", n: "Dune: Part Two", y: 2024, d: "Denis Villeneuve", rt: 166, mood: "scifi", svc: "Max", heat: 98, syn: "Paul Atreides joins the Fremen to wage war on those who destroyed his family, as prophecy tightens around him." },
  { tid: "t2", n: "Oppenheimer", y: 2023, d: "Christopher Nolan", rt: 180, mood: "tense", svc: "Prime", heat: 94, syn: "The father of the atomic bomb wrestles with the physics, the politics, and the fallout of his own creation." },
  { tid: "t3", n: "Poor Things", y: 2023, d: "Yorgos Lanthimos", rt: 141, mood: "mind", svc: "Hulu", heat: 89, syn: "A woman brought back to life sets out to see the world on her own defiantly strange terms." },
  { tid: "t4", n: "Glass Onion", y: 2022, d: "Rian Johnson", rt: 139, mood: "light", svc: "Netflix", heat: 86, syn: "Detective Benoit Blanc crashes a billionaire's island getaway, where a murder-mystery game turns very real." },
  { tid: "t5", n: "Top Gun: Maverick", y: 2022, d: "Joseph Kosinski", rt: 130, mood: "tense", svc: "Prime", heat: 84, syn: "A legendary pilot returns to train a new generation for a mission no one is expected to survive." },
  { tid: "t6", n: "Barbie", y: 2023, d: "Greta Gerwig", rt: 114, mood: "light", svc: "Max", heat: 82, syn: "Barbie leaves her perfect plastic world for the real one, where existence turns out to be a lot more complicated." },
  { tid: "t7", n: "The Menu", y: 2022, d: "Mark Mylod", rt: 107, mood: "tense", svc: "Hulu", heat: 77, syn: "A night at an exclusive island restaurant serves up courses with increasingly sinister intent." },
  { tid: "t8", n: "Past Lives", y: 2023, d: "Celine Song", rt: 105, mood: "light", svc: "Prime", heat: 74, syn: "Two childhood friends reunite decades later to weigh the lives they chose — and the one they didn't." },
  { tid: "t9", n: "The Banshees of Inisherin", y: 2022, d: "Martin McDonagh", rt: 114, mood: "tense", svc: "Max", heat: 71, syn: "On a small Irish island, a man abruptly ends a lifelong friendship, with quietly escalating consequences." },
  { tid: "t10", n: "Nope", y: 2022, d: "Jordan Peele", rt: 130, mood: "horror", svc: "Prime", heat: 68, syn: "Two siblings running a horse ranch try to capture proof of something impossible hanging in the sky." },
];


// Built-in catalog: a curated sample library spanning services and moods.
// Availability is sample data — a production build would pull live listings from TMDB/JustWatch.
export const CATALOG = [
  // A good time
  { n: "Superbad", y: 2007, d: "Greg Mottola", rt: 113, mood: "light", svc: "Netflix", syn: "Two friends chase one legendary party before high school ends." },
  { n: "The Grand Budapest Hotel", y: 2014, d: "Wes Anderson", rt: 99, mood: "light", svc: "Disney+", syn: "A legendary concierge and his lobby boy tumble through a pastel caper." },
  { n: "Groundhog Day", y: 1993, d: "Harold Ramis", rt: 101, mood: "light", svc: "Netflix", syn: "A cynical weatherman relives the same small-town day until he gets it right." },
  { n: "Ferris Bueller's Day Off", y: 1986, d: "John Hughes", rt: 103, mood: "light", svc: "Prime", syn: "One glorious day of hooky, one furious principal, one borrowed Ferrari." },
  { n: "Anchorman", y: 2004, d: "Adam McKay", rt: 94, mood: "light", svc: "Prime", syn: "A 70s newsman's world crumbles when a talented woman joins the desk." },
  { n: "Step Brothers", y: 2008, d: "Adam McKay", rt: 98, mood: "light", svc: "Max", syn: "Two middle-aged man-children become reluctant, then inseparable, brothers." },
  { n: "Bridesmaids", y: 2011, d: "Paul Feig", rt: 125, mood: "light", svc: "Hulu", syn: "A maid of honor's life unravels spectacularly on the road to the wedding." },
  { n: "Napoleon Dynamite", y: 2004, d: "Jared Hess", rt: 96, mood: "light", svc: "Hulu", syn: "An Idaho misfit helps his friend win class president, one dance at a time." },
  { n: "The Big Lebowski", y: 1998, d: "Joel Coen", rt: 117, mood: "light", svc: "Prime", syn: "The Dude just wants his rug back. The universe has other plans." },
  { n: "Hot Fuzz", y: 2007, d: "Edgar Wright", rt: 121, mood: "light", svc: "Netflix", syn: "A supercop is exiled to a sleepy village hiding a very tidy dark side." },
  { n: "21 Jump Street", y: 2012, d: "Lord & Miller", rt: 109, mood: "light", svc: "Max", syn: "Two hopeless cops go undercover in high school and swap social destinies." },
  { n: "Game Night", y: 2018, d: "Daley & Goldstein", rt: 100, mood: "light", svc: "Max", syn: "A competitive couple's game night collides with an actual kidnapping." },
  { n: "Crazy Rich Asians", y: 2018, d: "Jon M. Chu", rt: 120, mood: "light", svc: "Max", syn: "Meeting the boyfriend's family is harder when they're Singapore royalty-rich." },
  { n: "The Truman Show", y: 1998, d: "Peter Weir", rt: 103, mood: "light", svc: "Prime", syn: "A man slowly discovers his whole life is a television broadcast." },
  { n: "School of Rock", y: 2003, d: "Richard Linklater", rt: 110, mood: "light", svc: "Prime", syn: "A broke rocker fakes his way into teaching and forms a fifth-grade band." },
  { n: "Paddington 2", y: 2017, d: "Paul King", rt: 104, mood: "light", svc: "Netflix", syn: "A polite bear goes to prison and makes it a nicer place." },
  { n: "Chef", y: 2014, d: "Jon Favreau", rt: 114, mood: "light", svc: "Tubi", syn: "A burned-out chef rebuilds his life one food-truck sandwich at a time." },
  { n: "Juno", y: 2007, d: "Jason Reitman", rt: 96, mood: "light", svc: "Hulu", syn: "A sharp-tongued teenager navigates an unplanned pregnancy her own way." },
  { n: "Booksmart", y: 2019, d: "Olivia Wilde", rt: 102, mood: "light", svc: "Prime", syn: "Two overachievers cram four years of fun into one chaotic night." },
  { n: "Free Guy", y: 2021, d: "Shawn Levy", rt: 115, mood: "light", svc: "Disney+", syn: "A video game background character wakes up and decides to be the hero." },
  { n: "Little Miss Sunshine", y: 2006, d: "Dayton & Faris", rt: 101, mood: "light", svc: "Hulu", syn: "A gloriously dysfunctional family road-trips to a kids' beauty pageant." },
  { n: "Forrest Gump", y: 1994, d: "Robert Zemeckis", rt: 142, mood: "light", svc: "Prime", syn: "A gentle soul runs, quite literally, through decades of American history." },
  { n: "The Princess Bride", y: 1987, d: "Rob Reiner", rt: 98, mood: "light", svc: "Disney+", syn: "True love, fencing, giants, revenge — as you wish." },
  { n: "Ratatouille", y: 2007, d: "Brad Bird", rt: 111, mood: "light", svc: "Disney+", syn: "A rat with impeccable taste cooks his way through a Paris kitchen." },
  { n: "Up", y: 2009, d: "Pete Docter", rt: 96, mood: "light", svc: "Disney+", syn: "A grieving old man floats his house to South America; a stowaway helps." },
  { n: "Coco", y: 2017, d: "Lee Unkrich", rt: 105, mood: "light", svc: "Disney+", syn: "A boy crosses into the Land of the Dead to unlock his family's music." },
  { n: "Shrek", y: 2001, d: "Adamson & Jenson", rt: 90, mood: "light", svc: "Netflix", syn: "An ogre rescues a princess and accidentally learns to like people." },
  { n: "Elf", y: 2003, d: "Jon Favreau", rt: 97, mood: "light", svc: "Max", syn: "A human raised by elves takes Christmas cheer to Manhattan, loudly." },
  { n: "Home Alone", y: 1990, d: "Chris Columbus", rt: 103, mood: "light", svc: "Disney+", syn: "An eight-year-old defends his house with hardware-store brutality." },
  // There goes my dinner
  { n: "The Conjuring", y: 2013, d: "James Wan", rt: 112, mood: "horror", svc: "Max", syn: "Paranormal investigators face the darkest case of their careers." },
  { n: "Hereditary", y: 2018, d: "Ari Aster", rt: 127, mood: "horror", svc: "Prime", syn: "A family funeral pulls loose something that should have stayed buried." },
  { n: "A Quiet Place", y: 2018, d: "John Krasinski", rt: 90, mood: "horror", svc: "Prime", syn: "Make a sound, and the things that hunt by hearing will find you." },
  { n: "It", y: 2017, d: "Andy Muschietti", rt: 135, mood: "horror", svc: "Max", syn: "A clown in the sewers feeds on the children of a small town." },
  { n: "The Shining", y: 1980, d: "Stanley Kubrick", rt: 146, mood: "horror", svc: "Max", syn: "A winter caretaker's isolation curdles into murderous madness." },
  { n: "Scream", y: 1996, d: "Wes Craven", rt: 111, mood: "horror", svc: "Prime", syn: "A masked killer terrorizes teens who know the horror-movie rules by heart." },
  { n: "Halloween", y: 1978, d: "John Carpenter", rt: 91, mood: "horror", svc: "Tubi", syn: "The night he came home — and slasher cinema was never the same." },
  { n: "Saw", y: 2004, d: "James Wan", rt: 103, mood: "horror", svc: "Tubi", syn: "Two strangers wake chained in a room with terrible instructions." },
  { n: "Us", y: 2019, d: "Jordan Peele", rt: 116, mood: "horror", svc: "Netflix", syn: "A family's beach vacation is invaded by their own murderous doubles." },
  { n: "Midsommar", y: 2019, d: "Ari Aster", rt: 148, mood: "horror", svc: "Prime", syn: "A grieving woman's trip to a sunny Swedish festival goes very wrong." },
  { n: "The Babadook", y: 2014, d: "Jennifer Kent", rt: 94, mood: "horror", svc: "Tubi", syn: "A storybook monster feeds on a mother's grief and exhaustion." },
  { n: "Insidious", y: 2010, d: "James Wan", rt: 103, mood: "horror", svc: "Netflix", syn: "A comatose boy becomes a doorway for things from The Further." },
  { n: "Evil Dead Rise", y: 2023, d: "Lee Cronin", rt: 96, mood: "horror", svc: "Max", syn: "The Book of the Dead turns a family high-rise into a bloodbath." },
  { n: "Smile", y: 2022, d: "Parker Finn", rt: 115, mood: "horror", svc: "Prime", syn: "A curse passes from victim to witness, always grinning." },
  { n: "Talk to Me", y: 2023, d: "Danny & Michael Philippou", rt: 95, mood: "horror", svc: "Netflix", syn: "Teens use an embalmed hand to touch the dead — as a party game." },
  { n: "The Ring", y: 2002, d: "Gore Verbinski", rt: 115, mood: "horror", svc: "Prime", syn: "Watch the tape, answer the phone, and you have seven days." },
  { n: "Sinister", y: 2012, d: "Scott Derrickson", rt: 110, mood: "horror", svc: "Hulu", syn: "A true-crime writer finds home movies no one should ever watch." },
  { n: "28 Days Later", y: 2002, d: "Danny Boyle", rt: 113, mood: "horror", svc: "Prime", syn: "A man wakes from a coma into a London emptied by rage." },
  { n: "Train to Busan", y: 2016, d: "Yeon Sang-ho", rt: 118, mood: "horror", svc: "Prime", syn: "A father and daughter fight through a zombie outbreak at 300 km/h." },
  { n: "The Witch", y: 2015, d: "Robert Eggers", rt: 92, mood: "horror", svc: "Max", syn: "A Puritan family unravels at the edge of a wood that watches back." },
  // Warp speed
  { n: "Interstellar", y: 2014, d: "Christopher Nolan", rt: 169, mood: "scifi", svc: "Prime", syn: "A pilot leaves a dying Earth to find humanity a new home beyond a wormhole." },
  { n: "The Matrix", y: 1999, d: "The Wachowskis", rt: 136, mood: "scifi", svc: "Max", syn: "A hacker learns reality is a simulation — and he might be the anomaly." },
  { n: "Blade Runner 2049", y: 2017, d: "Denis Villeneuve", rt: 164, mood: "scifi", svc: "Netflix", syn: "A replicant cop uncovers a secret that could unravel society." },
  { n: "Inception", y: 2010, d: "Christopher Nolan", rt: 148, mood: "scifi", svc: "Max", syn: "A thief who steals from dreams takes one last job: planting an idea." },
  { n: "Edge of Tomorrow", y: 2014, d: "Doug Liman", rt: 113, mood: "scifi", svc: "Max", syn: "A soldier relives the same alien battle, dying his way to victory." },
  { n: "The Martian", y: 2015, d: "Ridley Scott", rt: 144, mood: "scifi", svc: "Hulu", syn: "Stranded on Mars, an astronaut sciences the hell out of survival." },
  { n: "Ex Machina", y: 2014, d: "Alex Garland", rt: 108, mood: "scifi", svc: "Prime", syn: "A coder tests a beautiful AI — or is it the other way around?" },
  { n: "District 9", y: 2009, d: "Neill Blomkamp", rt: 112, mood: "scifi", svc: "Netflix", syn: "An alien refugee camp bureaucrat starts becoming what he polices." },
  { n: "Looper", y: 2012, d: "Rian Johnson", rt: 119, mood: "scifi", svc: "Netflix", syn: "A hitman for the mob of the future meets his next target: himself." },
  { n: "Star Wars: A New Hope", y: 1977, d: "George Lucas", rt: 121, mood: "scifi", svc: "Disney+", syn: "A farm boy, a princess, a smuggler, and a battle station's fatal flaw." },
  { n: "Rogue One", y: 2016, d: "Gareth Edwards", rt: 133, mood: "scifi", svc: "Disney+", syn: "The stolen plans that started it all, paid for in full." },
  { n: "Guardians of the Galaxy", y: 2014, d: "James Gunn", rt: 121, mood: "scifi", svc: "Disney+", syn: "A ragtag crew of losers accidentally saves the galaxy, to a killer mixtape." },
  { n: "Back to the Future", y: 1985, d: "Robert Zemeckis", rt: 116, mood: "scifi", svc: "Netflix", syn: "A teen's DeLorean trip to 1955 nearly erases his own existence." },
  { n: "Alien", y: 1979, d: "Ridley Scott", rt: 117, mood: "scifi", svc: "Hulu", syn: "In space, no one can hear you scream." },
  { n: "Aliens", y: 1986, d: "James Cameron", rt: 137, mood: "scifi", svc: "Hulu", syn: "Ripley goes back — this time with marines, and this time it's war." },
  { n: "Minority Report", y: 2002, d: "Steven Spielberg", rt: 145, mood: "scifi", svc: "Prime", syn: "A cop who arrests murderers before they act is accused of a future crime." },
  { n: "Children of Men", y: 2006, d: "Alfonso Cuarón", rt: 109, mood: "scifi", svc: "Prime", syn: "In a world without births, one pregnant woman must be protected." },
  { n: "Snowpiercer", y: 2013, d: "Bong Joon-ho", rt: 126, mood: "scifi", svc: "Netflix", syn: "Humanity's frozen remnant rides one train, and revolt moves car by car." },
  { n: "Prometheus", y: 2012, d: "Ridley Scott", rt: 124, mood: "scifi", svc: "Hulu", syn: "Scientists seek humanity's makers and find something far less friendly." },
  { n: "Avatar", y: 2009, d: "James Cameron", rt: 162, mood: "scifi", svc: "Disney+", syn: "A paralyzed marine's second body pulls him between two worlds at war." },
  // Tense & gripping
  { n: "The Dark Knight", y: 2008, d: "Christopher Nolan", rt: 152, mood: "tense", svc: "Max", syn: "Batman meets an agent of chaos who just wants to watch the world burn." },
  { n: "Se7en", y: 1995, d: "David Fincher", rt: 127, mood: "tense", svc: "Max", syn: "Two detectives hunt a killer preaching through the seven deadly sins." },
  { n: "Gone Girl", y: 2014, d: "David Fincher", rt: 149, mood: "tense", svc: "Netflix", syn: "A wife vanishes and a marriage's picture-perfect surface cracks open." },
  { n: "Zodiac", y: 2007, d: "David Fincher", rt: 157, mood: "tense", svc: "Netflix", syn: "An unsolved killer consumes the men who can't stop chasing him." },
  { n: "Heat", y: 1995, d: "Michael Mann", rt: 170, mood: "tense", svc: "Max", syn: "A master thief and a relentless detective circle one last score." },
  { n: "The Departed", y: 2006, d: "Martin Scorsese", rt: 151, mood: "tense", svc: "Prime", syn: "A cop inside the mob, a mole inside the police, one city between them." },
  { n: "No Country for Old Men", y: 2007, d: "Coen Brothers", rt: 122, mood: "tense", svc: "Prime", syn: "A satchel of drug money draws an implacable killer across Texas." },
  { n: "Prisoners", y: 2013, d: "Denis Villeneuve", rt: 153, mood: "tense", svc: "Netflix", syn: "When his daughter vanishes, a father decides the law is too slow." },
  { n: "Nightcrawler", y: 2014, d: "Dan Gilroy", rt: 117, mood: "tense", svc: "Tubi", syn: "A hungry freelancer films LA's worst nights — then starts arranging them." },
  { n: "Uncut Gems", y: 2019, d: "Safdie Brothers", rt: 135, mood: "tense", svc: "Netflix", syn: "A jeweler with a gambling problem bets everything, constantly, at once." },
  { n: "Wind River", y: 2017, d: "Taylor Sheridan", rt: 107, mood: "tense", svc: "Netflix", syn: "A tracker and a rookie agent hunt a killer across frozen Wyoming." },
  { n: "Hell or High Water", y: 2016, d: "David Mackenzie", rt: 102, mood: "tense", svc: "Prime", syn: "Two brothers rob the very banks foreclosing on their family land." },
  { n: "The Town", y: 2010, d: "Ben Affleck", rt: 125, mood: "tense", svc: "Max", syn: "A Boston bank robber falls for the one witness who could end him." },
  { n: "Argo", y: 2012, d: "Ben Affleck", rt: 120, mood: "tense", svc: "Max", syn: "The CIA fakes a movie to smuggle diplomats out of revolutionary Iran." },
  { n: "Baby Driver", y: 2017, d: "Edgar Wright", rt: 113, mood: "tense", svc: "Netflix", syn: "A getaway driver who runs on music tries to steer out of the life." },
  { n: "John Wick", y: 2014, d: "Chad Stahelski", rt: 101, mood: "tense", svc: "Prime", syn: "They took his car and killed his dog. Big mistake." },
  { n: "Mission: Impossible – Fallout", y: 2018, d: "Christopher McQuarrie", rt: 147, mood: "tense", svc: "Prime", syn: "Ethan Hunt free-falls, cliff-hangs, and helicopter-duels to save millions." },
  { n: "Casino Royale", y: 2006, d: "Martin Campbell", rt: 144, mood: "tense", svc: "Prime", syn: "Bond earns his 00 status across a brutal poker game with global stakes." },
  { n: "The Fugitive", y: 1993, d: "Andrew Davis", rt: 130, mood: "tense", svc: "Max", syn: "A wrongly convicted surgeon runs while hunting his wife's real killer." },
  { n: "Knives Out", y: 2019, d: "Rian Johnson", rt: 130, mood: "tense", svc: "Prime", syn: "A famous detective probes a mystery-writer's very suspicious family." },
  // Mind-bending
  { n: "Memento", y: 2000, d: "Christopher Nolan", rt: 113, mood: "mind", svc: "Tubi", syn: "A man without short-term memory hunts a killer using notes and tattoos." },
  { n: "Eternal Sunshine of the Spotless Mind", y: 2004, d: "Michel Gondry", rt: 108, mood: "mind", svc: "Prime", syn: "Two ex-lovers erase each other — and fight the erasure from inside it." },
  { n: "Shutter Island", y: 2010, d: "Martin Scorsese", rt: 138, mood: "mind", svc: "Netflix", syn: "A marshal investigates an island asylum where nothing adds up." },
  { n: "Donnie Darko", y: 2001, d: "Richard Kelly", rt: 113, mood: "mind", svc: "Tubi", syn: "A giant rabbit tells a troubled teen exactly when the world ends." },
  { n: "The Prestige", y: 2006, d: "Christopher Nolan", rt: 130, mood: "mind", svc: "Max", syn: "Two rival magicians destroy themselves perfecting one impossible trick." },
  { n: "Predestination", y: 2014, d: "Spierig Brothers", rt: 97, mood: "mind", svc: "Prime", syn: "A time agent's final mission folds into itself like a paradox." },
  { n: "Source Code", y: 2011, d: "Duncan Jones", rt: 93, mood: "mind", svc: "Netflix", syn: "A soldier relives eight minutes of a train bombing until he finds the bomber." },
  { n: "Enemy", y: 2013, d: "Denis Villeneuve", rt: 91, mood: "mind", svc: "Tubi", syn: "A professor discovers his exact double, and their lives start to blur." },
  { n: "Primer", y: 2004, d: "Shane Carruth", rt: 77, mood: "mind", svc: "Tubi", syn: "Two engineers build time travel in a garage and immediately regret it." },
  { n: "Annihilation", y: 2018, d: "Alex Garland", rt: 115, mood: "mind", svc: "Netflix", syn: "Scientists enter a shimmer where biology itself rewrites the rules." },
];

export const NO_SYN = "No synopsis on file — a mystery even to the archive.";

export const C = {
  bg: "#0D0F1E", glow: "#1B2040", panel: "#171B31", panelHi: "#1F2542",
  edge: "#2C3255", edgeHi: "#3D4472", text: "#F0F1FA", muted: "#9CA2C7",
  faint: "#666D99", amber: "#FFB627", amberSoft: "#FFD37A", red: "#E4572E",
  green: "#43C088", paper: "#F3EBDA", paperEdge: "#D8CBAF", ink: "#221E14", inkSoft: "#6B6350",
};

export const MOODS = {
  action: "Action", adventure: "Adventure", animation: "Animation", light: "Comedy",
  crime: "Crime", documentary: "Documentary", drama: "Drama", family: "Family",
  fantasy: "Fantasy", history: "History", horror: "Horror", music: "Music",
  mind: "Mystery", romance: "Romance", scifi: "Sci-fi", tense: "Thriller",
  war: "War", western: "Western",
};

